name: Docker Image CI v4.3

on:
  push:
    branches: [ v4.3 ]
  pull_request:
    branches: [ v4.3 ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        file: Dockerfile
        tags: mindthecap/mitre-attack-navigator:v4.3
